name: travel_ui
description: Travel UI project


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  font_awesome_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/images/
  uses-material-design: true

 